# Meta Data for SEO

## Homepage
title = "Programación Competitiva UChile"
titleSeparator = "-"
logo = "images/banner.svg"
titleAddition = "Inicio"
description = "Grupo organizado de Programación Competitiva en la Universidad de Chile."

## Open Graph
images = ["logo_redondo.png"]
ogLocale = "es_CL"
domainTLD = "doks.netlify.app"
titleHome = "Programación Competitiva UChile"

## Twitter Cards
twitterSite = "@dccuchile"
twitterCreator = "@dccuchile"

schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Sitio generado con <a href=\"https://gohugo.io/\">Hugo</a> y <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertDismissable = true
alertText = ""

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/progcompuch/apunte"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["apunte", "recursos"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = true
